import type { Metadata } from "next";
import "./globals.css";
import { CalculatorProvider } from "@/contexts/CalculatorContext";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={`${inter.className} min-h-screen antialiased`}>
        <div className="flex flex-col min-h-screen">
          <CalculatorProvider>
            <main className="flex-1 w-full">
              {children}
            </main>
          </CalculatorProvider>
        </div>
      </body>
    </html>
  );
}